
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_COL ALERTA_PARA AND DEF DESLIGAR DIFUNDIR DISPOSITIVOS DOIS_PONTOS EM EXECUTE FALSE FECHA_COL FIMDISPOSITIVOS ID IGUAL LIGAR MSG NUM OP_EQ OP_GE OP_GT OP_LE OP_LT OP_NE PT_VIRG QUANDO SENAO SETINHA TRUE VIRGULAprogram : DEV_SECDEV_SEC : DISPOSITIVOS DOIS_PONTOS DEV_LIST FIMDISPOSITIVOSDEV_LIST : DEVICE DEV_LIST\n| DEVICEDEVICE : ID_DEVICE\n| ID_DEVICE ABRE_COL ID_OBS FECHA_COLID_DEVICE : IDID_OBS : ID'
    
_lr_action_items = {'DISPOSITIVOS':([0,],[3,]),'$end':([1,2,9,],[0,-1,-2,]),'DOIS_PONTOS':([3,],[4,]),'ID':([4,6,7,8,11,14,],[8,8,-5,-7,13,-6,]),'FIMDISPOSITIVOS':([5,6,7,8,10,14,],[9,-4,-5,-7,-3,-6,]),'ABRE_COL':([7,8,],[11,-7,]),'FECHA_COL':([12,13,],[14,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'DEV_SEC':([0,],[2,]),'DEV_LIST':([4,6,],[5,10,]),'DEVICE':([4,6,],[6,6,]),'ID_DEVICE':([4,6,],[7,7,]),'ID_OBS':([11,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> DEV_SEC','program',1,'p_program','analisador.py',179),
  ('DEV_SEC -> DISPOSITIVOS DOIS_PONTOS DEV_LIST FIMDISPOSITIVOS','DEV_SEC',4,'p_dev_sec','analisador.py',183),
  ('DEV_LIST -> DEVICE DEV_LIST','DEV_LIST',2,'p_dev_list','analisador.py',189),
  ('DEV_LIST -> DEVICE','DEV_LIST',1,'p_dev_list','analisador.py',190),
  ('DEVICE -> ID_DEVICE','DEVICE',1,'p_device','analisador.py',197),
  ('DEVICE -> ID_DEVICE ABRE_COL ID_OBS FECHA_COL','DEVICE',4,'p_device','analisador.py',198),
  ('ID_DEVICE -> ID','ID_DEVICE',1,'p_id_device','analisador.py',210),
  ('ID_OBS -> ID','ID_OBS',1,'p_id_obs','analisador.py',214),
]
